version: '2.2'

# Kafka Cluster

services:

  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  zookeeper-2:
    image: confluentinc/cp-zookeeper:5.5.0
    container_name: zookeeper-2
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka-1:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka-1
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - "9092:9092"
    healthcheck:
      test: "/usr/bin/kafka-topics --list --zookeeper zookeeper-1:2181"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-2:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka-2
    depends_on:
      - zookeeper-1
      - zookeeper-2
    ports:
      - "9093:9093"
    healthcheck:
      test: "/usr/bin/kafka-topics --list --zookeeper zookeeper-1:2181"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

# Kafka Topic Create
      
  kafka-topics:
    image: confluentinc/cp-kafka:5.5.0
    container_name: kafka-topics
    depends_on:
      kafka-1:
        condition: service_healthy
    command: "bash -c 'echo creating topics && \
      kafka-topics --bootstrap-server kafka-1:29092 --create --topic submitted-orders && \
      kafka-topics --bootstrap-server kafka-1:29092 --create --topic validated-orders && \
      kafka-topics --bootstrap-server kafka-1:29092 --create --topic accepted-orders && \
      kafka-topics --bootstrap-server kafka-1:29092 --create --topic orders-reports'"
